/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package device;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author denia
 */
public class GuiDenis extends javax.swing.JFrame {

    /**
     * Creates new form GuiDenis
     */
    public GuiDenis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        brandText = new javax.swing.JTextField();
        modelText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        alimentareText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        putereText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        pornireText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        latimeTaiereText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        culoareText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        pretText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        garantieText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        categorieText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        masiniTunsIarba = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        populateTableButton = new javax.swing.JButton();
        SalvareButon = new javax.swing.JButton();
        sortButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        pretFiltrare = new javax.swing.JTextField();
        latimeTaiereFiltrare = new javax.swing.JTextField();
        ClearTableButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        putereFiltrare = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        brandMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        modelMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
        tipPornireMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        tipAlimentareMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel20 = new javax.swing.JLabel();
        capacitateCilindricaMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel21 = new javax.swing.JLabel();
        putereMotorMotosapaText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        motosapeTable = new javax.swing.JTable();
        javax.swing.JLabel jLabel22 = new javax.swing.JLabel();
        numarVitezeMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel23 = new javax.swing.JLabel();
        pretMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel24 = new javax.swing.JLabel();
        garantieMotosapaText = new javax.swing.JTextField();
        javax.swing.JLabel jLabel25 = new javax.swing.JLabel();
        categorieMotosapaText = new javax.swing.JTextField();
        afisareTabelMotosapeButton = new javax.swing.JButton();
        eliberareTableMotosapeButton = new javax.swing.JButton();
        addMotosapaButton = new javax.swing.JButton();
        deleteMotosapaButton = new javax.swing.JButton();
        SaveListaMotosapeButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel26 = new javax.swing.JLabel();
        tipAlimentareMotosapeFilter = new javax.swing.JTextField();
        javax.swing.JLabel jLabel27 = new javax.swing.JLabel();
        pretMotosapaFilter = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        tipPornireMotosapaFiltrare = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date Campuri :");

        jLabel2.setText("Brand : ");

        jLabel3.setText("Model :");

        jLabel4.setText("TipAlimentare :");

        jLabel5.setText("Putere :");

        jLabel6.setText("TipPornire");

        jLabel7.setText("Latime Taiere :");

        jLabel8.setText("Culoare :");

        culoareText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                culoareTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Pret :");

        jLabel10.setText("Garantie :");

        jLabel11.setText("Categorie :");

        masiniTunsIarba.setAutoCreateRowSorter(true);
        masiniTunsIarba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model", "Tip Alimentare", "Putere", "Tip Pornire", "Latime Taiere", "Culoare", "Pret ", "Garantie", "Categorie"
            }
        ));
        jScrollPane1.setViewportView(masiniTunsIarba);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        populateTableButton.setText("Afisare elemente");
        populateTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateTableButtonActionPerformed(evt);
            }
        });

        SalvareButon.setText("Save");
        SalvareButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvareButonActionPerformed(evt);
            }
        });

        sortButton.setText("Sort");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Pret :");

        jLabel13.setText("Latime de taiere mai mare decat :");

        ClearTableButton.setText("Eliberare Tabel");
        ClearTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTableButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Putere:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pornireText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(latimeTaiereText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(culoareText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pretText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(garantieText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categorieText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(16, 16, 16)
                                .addComponent(modelText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alimentareText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(putereText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(populateTableButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(ClearTableButton))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(AddButton)
                                        .addGap(31, 31, 31)
                                        .addComponent(DeleteButton)
                                        .addGap(62, 62, 62)
                                        .addComponent(SalvareButon)))
                                .addGap(122, 122, 122)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(latimeTaiereFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sortButton)
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(36, 36, 36)
                                        .addComponent(pretFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(putereFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(modelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(alimentareText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(putereText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pornireText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(latimeTaiereText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(culoareText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(pretText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(garantieText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(categorieText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(populateTableButton)
                    .addComponent(jLabel12)
                    .addComponent(pretFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearTableButton)
                    .addComponent(jLabel14)
                    .addComponent(putereFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddButton)
                        .addComponent(DeleteButton)
                        .addComponent(SalvareButon)
                        .addComponent(sortButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(latimeTaiereFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MasiniTunsIarba", jPanel2);

        jLabel15.setText("Date Campuri :");

        jLabel16.setText("Brand :");

        jLabel17.setText("Model :");

        jLabel18.setText("Tip Pornire");

        jLabel19.setText("Tip Alimentare");

        jLabel20.setText("Capacitate cilindrica");

        jLabel21.setText("Putere Motor");

        motosapeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model", "Tip Pornire", "Tip Alimentare", "Capacitate cilindrica", "Putere Motor", "Numar viteze", "Pret", "Garantie", "Categorie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.Float.class, java.lang.Byte.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(motosapeTable);

        jLabel22.setText("Numar viteze: ");

        jLabel23.setText("Pret :");

        jLabel24.setText("Garantie :");

        jLabel25.setText("Categorie :");

        afisareTabelMotosapeButton.setText("Afisare tabel");
        afisareTabelMotosapeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisareTabelMotosapeButtonActionPerformed(evt);
            }
        });

        eliberareTableMotosapeButton.setText("Eliberare tabel");
        eliberareTableMotosapeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliberareTableMotosapeButtonActionPerformed(evt);
            }
        });

        addMotosapaButton.setText("Add");
        addMotosapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMotosapaButtonActionPerformed(evt);
            }
        });

        deleteMotosapaButton.setText("Delete");
        deleteMotosapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMotosapaButtonActionPerformed(evt);
            }
        });

        SaveListaMotosapeButton.setText("Save");
        SaveListaMotosapeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveListaMotosapeButtonActionPerformed(evt);
            }
        });

        jLabel26.setText("TipAlimentare");

        jLabel27.setText("Pret");

        jButton6.setText("Sort");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel28.setText("Tip pornire");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(putereMotorMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(brandMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numarVitezeMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pretMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(garantieMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(modelMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipPornireMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipAlimentareMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(capacitateCilindricaMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categorieMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(addMotosapaButton)
                                .addGap(27, 27, 27)
                                .addComponent(deleteMotosapaButton)
                                .addGap(59, 59, 59)
                                .addComponent(SaveListaMotosapeButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(afisareTabelMotosapeButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(eliberareTableMotosapeButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(384, 384, 384)
                                    .addComponent(jLabel28))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tipPornireMotosapaFiltrare, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pretMotosapaFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(jButton6))
                            .addComponent(tipAlimentareMotosapeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)))
                .addContainerGap(0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(brandMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(modelMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tipPornireMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tipAlimentareMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(capacitateCilindricaMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(putereMotorMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(numarVitezeMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(pretMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(garantieMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(categorieMotosapaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addMotosapaButton)
                                    .addComponent(deleteMotosapaButton)
                                    .addComponent(SaveListaMotosapeButton))
                                .addGap(59, 59, 59))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(afisareTabelMotosapeButton)
                                    .addComponent(eliberareTableMotosapeButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipAlimentareMotosapeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pretMotosapaFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipPornireMotosapaFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Motosape", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void culoareTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_culoareTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_culoareTextActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String brand = brandText.getText();
        String model = modelText.getText();
        String alimentare = alimentareText.getText();
        byte putere = Byte.parseByte(putereText.getText());
        String pornire = pornireText.getText();
        byte latimeTaiere = Byte.parseByte(latimeTaiereText.getText());
        String culoare = culoareText.getText();
        float pret = Float.parseFloat(pretText.getText());
        byte garantie = Byte.parseByte(garantieText.getText());
        String categorie = categorieText.getText();
        //BUTONUL DE ADAUGARE A UNUI NOU ELEMENT IN TABEL , DUPA ADAUGARE , ELIBEREAZA CASETELE DE VALORI 
        if(brand.isEmpty() || model.isEmpty() || alimentare.isEmpty() || putere == 0 || pornire.isEmpty() || latimeTaiere == 0 || culoare.isEmpty() || pret == 0 || garantie == 0 || categorie.isEmpty()){
            JOptionPane.showMessageDialog(this,
                                            "Completati toate campurile",
                                                "Incercati din nou ",//EROARE IN CAZ DE NU AM COMPLETAT TOATE CASETELE 
                                                JOptionPane.ERROR_MESSAGE);
                                                
        }else{
        DefaultTableModel modelTabela = (DefaultTableModel) masiniTunsIarba.getModel();
        modelTabela.addRow(new Object[] {brand, model, alimentare, putere, pornire, latimeTaiere, culoare, pret, garantie, categorie});
        MasinaTunsIarba masina = new MasinaTunsIarba(brand, model, alimentare, putere, pornire, latimeTaiere, culoare, pret, garantie, categorie);
        listaMasiniTunsIarba.add(masina); lengthMasiniTunsIarbaArray++;
        }
        brandText.setText("");
        modelText.setText("");
        alimentareText.setText("");
        putereText.setText("");
        pornireText.setText("");
        latimeTaiereText.setText("");
        culoareText.setText("");
        pretText.setText("");
        garantieText.setText("");
        categorieText.setText("");
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int linie = masiniTunsIarba.getSelectedRow();
        if(linie < 0){//BUTON DE STERGERE A UNUI RAND DIN TABEL
        JOptionPane.showMessageDialog(this,
                                        "Selecteaza o linie",
                                        "Eroare nu ati selectat nicio linie !",
                                        JOptionPane.ERROR_MESSAGE);//EROARE IN CAZ DE NU AM SELECTAT NICIUN RAND 
        }else{
            DefaultTableModel modelTabela = (DefaultTableModel) masiniTunsIarba.getModel();
            modelTabela.removeRow(linie); lengthMasiniTunsIarbaArray--;
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void populateTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateTableButtonActionPerformed
        // TODO add your handling code here:
        incarcareMasiniTunsIarbaTabel();
    }//GEN-LAST:event_populateTableButtonActionPerformed

    private void SalvareButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvareButonActionPerformed
        // TODO add your handling code here:

       
         try (BufferedWriter writer = new BufferedWriter(new FileWriter("C:\\Users\\denia\\Documents\\tttt\\Device\\DateMasiniTunsIarba.csv"))) {
        for (int i = 0; i < lengthMasiniTunsIarbaArray; i++) {
            MasinaTunsIarba product = listaMasiniTunsIarba.get(i);
            writer.write(product.afisare());
            writer.newLine();
}
        //rowsDeleted=0;
    } catch (IOException e) {
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_SalvareButonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelTabela = (DefaultTableModel) masiniTunsIarba.getModel();//MAI INTAI ELIBERAM TABELUL SA NU SE ADAUGE INCONTINUARE
        clearTable(modelTabela);//BUTONUL DE SORTARE ; IA VALOARE DIN CAMPURILE MENTIONATE SI LE PUNE PE POST DE CONDITIE PENTRU AFISARE
        float pret = Float.parseFloat(pretFiltrare.getText());
        byte lungime = Byte.parseByte(latimeTaiereFiltrare.getText());
        float putere = Float.parseFloat(putereFiltrare.getText());
        
        for (MasinaTunsIarba item : listaMasiniTunsIarba){
                if(item.getPret()>=pret && item.getLatimeTaiere()>=lungime && item.getPutereMotor()>=putere){
                
                Object linie[] = new Object[10]; 
                
                linie[0]=item.getBrand();
                linie[1]=item.getModel();
                linie[2]=item.getTipAlimentare();
                linie[3]=item.getPutereMotor();
                linie[4]=item.getTipPornire();
                linie[5]=item.getLatimeTaiere();
                linie[6]=item.getCuloare();
                linie[7]=item.getPret();
                linie[8]=item.getGarantie();
                linie[9]=item.getCategorie();
                modelTabela.addRow(linie);
                
                }
                    
        }
        pretFiltrare.setText("");
        latimeTaiereFiltrare.setText("");
        putereFiltrare.setText("");
        
    }//GEN-LAST:event_sortButtonActionPerformed

    private void ClearTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTableButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelTabela = (DefaultTableModel) masiniTunsIarba.getModel();//BUTONUL PENTRU ELIBERAREA TABELULUI
        clearTable(modelTabela);//APELEAZA METODA DE ELIBERARE A TABELULUI
    }//GEN-LAST:event_ClearTableButtonActionPerformed

    private void afisareTabelMotosapeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisareTabelMotosapeButtonActionPerformed
        // TODO add your handling code here:
        incarcareMotosapeTabel();
        
    }//GEN-LAST:event_afisareTabelMotosapeButtonActionPerformed
public void incarcareMotosapeTabel(){ // METODA PENTRU A INCARCA ELEMENTELE IN TABEL ; IAU FIECARE ELEMENT 
    DefaultTableModel model = (DefaultTableModel) motosapeTable.getModel();//DIN ARRAYLIST SI IL INSEREZ IN MODELUL DE TABEL
    Object linie[] = new Object[10]; //String brand,String model, String tipPornire, String tipAlimentare, int capacitateCilindrica, byte putereMotor, byte numarViteze,  float pret, byte garantie, String categorie
    for(int i = 0 ; i<listaMotosapa.size(); i++ ){
        linie[0]=listaMotosapa.get(i).getBrand();
        linie[1]=listaMotosapa.get(i).getModel();
        linie[2]=listaMotosapa.get(i).getTipPornire();
        linie[3]=listaMotosapa.get(i).getTipAlimentare();
        linie[4]=listaMotosapa.get(i).getPutereMotor();
        linie[5]=listaMotosapa.get(i).getCapacitateCilindrica();
        linie[6]=listaMotosapa.get(i).getNumarViteze();
        linie[7]=listaMotosapa.get(i).getPret();
        linie[8]=listaMotosapa.get(i).getGarantie();
        linie[9]=listaMotosapa.get(i).getCategorie();
        model.addRow(linie);
    }}
    private void deleteMotosapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMotosapaButtonActionPerformed
        // TODO add your handling code here:
        int linie = motosapeTable.getSelectedRow();
        if(linie < 0){//BUTON DE STERGERE A UNUI RAND DIN TABEL
        JOptionPane.showMessageDialog(this,
                                        "Selecteaza o linie",
                                        "Eroare nu ati selectat nicio linie !",
                                        JOptionPane.ERROR_MESSAGE);//EROARE IN CAZ DE NU AM SELECTAT NICIUN RAND 
        }else{
            DefaultTableModel modelTabela = (DefaultTableModel) motosapeTable.getModel();
            modelTabela.removeRow(linie); lengthMotosapeArray--;
        }
    }//GEN-LAST:event_deleteMotosapaButtonActionPerformed

    private void SaveListaMotosapeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveListaMotosapeButtonActionPerformed
        // TODO add your handling code here:
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("C:\\Users\\denia\\Documents\\tttt\\Device\\DateMasiniTunsIarba.csv"))) {
        for (int i = 0; i < lengthMotosapeArray; i++) {
            Motosapa product = listaMotosapa.get(i);
            writer.write(product.afisare());
            writer.newLine();
}
        //rowsDeleted=0;
    } catch (IOException e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_SaveListaMotosapeButtonActionPerformed

    private void addMotosapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMotosapaButtonActionPerformed
        // TODO add your handling code here:
        String brand = brandMotosapaText.getText();
        String model = modelMotosapaText.getText();
        String tipPornire = tipPornireMotosapaText.getText();
        String tipAlimentare = tipAlimentareMotosapaText.getText();
        int capacitateCilindrica = Integer.parseInt(capacitateCilindricaMotosapaText.getText());
        byte putereMotor = Byte.parseByte(putereMotorMotosapaText.getText());
        byte numarViteze = Byte.parseByte(numarVitezeMotosapaText.getText());
        float pret = Float.parseFloat(pretMotosapaText.getText());
        byte garantie = Byte.parseByte(garantieMotosapaText.getText());
        String categorie = categorieMotosapaText.getText();
        //BUTONUL DE ADAUGARE A UNUI NOU ELEMENT IN TABEL , DUPA ADAUGARE , ELIBEREAZA CASETELE DE VALORI 
        if(brand.isEmpty() || model.isEmpty() || tipPornire.isEmpty() || tipAlimentare.isEmpty() || capacitateCilindrica == 0 || putereMotor == 0 || numarViteze == 0  || pret == 0 || garantie == 0 || categorie.isEmpty()){
            JOptionPane.showMessageDialog(this,
                                            "Completati toate campurile",
                                                "Incercati din nou ",//EROARE IN CAZ DE NU AM COMPLETAT TOATE CASETELE 
                                                JOptionPane.ERROR_MESSAGE);
                                                
        }else{
        DefaultTableModel modelTabela = (DefaultTableModel) motosapeTable.getModel();
        modelTabela.addRow(new Object[] {brand, model, tipPornire, tipAlimentare, capacitateCilindrica, putereMotor, numarViteze, pret, garantie, categorie});
        Motosapa motosapa = new Motosapa(brand, model, tipPornire, tipAlimentare, capacitateCilindrica, putereMotor, numarViteze, pret, garantie, categorie);
        listaMotosapa.add(motosapa); lengthMotosapeArray++;
        }
        brandMotosapaText.setText("");
        modelMotosapaText.setText("");
        tipPornireMotosapaText.setText("");
        tipAlimentareMotosapaText.setText("");
        capacitateCilindricaMotosapaText.setText("");
        putereMotorMotosapaText.setText("");
        numarVitezeMotosapaText.setText("");
        pretMotosapaText.setText("");
        garantieMotosapaText.setText("");
        categorieMotosapaText.setText("");
        
    }//GEN-LAST:event_addMotosapaButtonActionPerformed

    private void eliberareTableMotosapeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliberareTableMotosapeButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelTabela = (DefaultTableModel) motosapeTable.getModel();//BUTONUL PENTRU ELIBERAREA TABELULUI
        clearTable(modelTabela);//APELEAZA METODA DE ELIBERARE A TABELULUI
    }//GEN-LAST:event_eliberareTableMotosapeButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelTabela = (DefaultTableModel) motosapeTable.getModel();//MAI INTAI ELIBERAM TABELUL SA NU SE ADAUGE INCONTINUARE
        clearTable(modelTabela);//BUTONUL DE SORTARE ; IA VALOARE DIN CAMPURILE MENTIONATE SI LE PUNE PE POST DE CONDITIE PENTRU AFISARE
        
        String tipAlimentare = tipAlimentareMotosapeFilter.getText();
        float pret = Float.parseFloat(pretMotosapaFilter.getText());
        String tipPornire = tipPornireMotosapaFiltrare.getText();
        
        for (Motosapa item : listaMotosapa){
                if(item.getPret()>=pret && item.getTipAlimentare().equals(tipAlimentare) && item.getTipPornire().equals(tipPornire)){
                
                Object linie[] = new Object[10]; 
                
                linie[0]=item.getBrand();
                linie[1]=item.getModel();
                linie[2]=item.getTipPornire();
                linie[3]=item.getPutereMotor();
                linie[4]=item.getTipAlimentare();
                linie[5]=item.getCapacitateCilindrica();
                linie[6]=item.getNumarViteze();
                linie[7]=item.getPret();
                linie[8]=item.getGarantie();
                linie[9]=item.getCategorie();
                
                modelTabela.addRow(linie);
                }
               
        }
        tipAlimentareMotosapeFilter.setText("");
        pretMotosapaFilter.setText("");
        tipPornireMotosapaFiltrare.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static ArrayList<MasinaTunsIarba> listaMasiniTunsIarba = new ArrayList<>();
    public static ArrayList<Motosapa> listaMotosapa = new ArrayList<>();
    public static int lengthMasiniTunsIarbaArray = 0;
    public static int lengthMotosapeArray = 0;
    
    public void clearTable(DefaultTableModel model){//METODA DE ELIBERARE A TABELULUI , SA NU IMI MAI AFISEZE NIMIC
     model.setRowCount(0);
    }
    
    public void incarcareMasiniTunsIarbaTabel(){ // METODA PENTRU A INCARCA ELEMENTELE IN TABEL ; IAU FIECARE ELEMENT 
    DefaultTableModel model = (DefaultTableModel) masiniTunsIarba.getModel();//DIN ARRAYLIST SI IL INSEREZ IN MODELUL DE TABEL
    Object linie[] = new Object[10]; 
    for(int i = 0 ; i<listaMasiniTunsIarba.size(); i++ ){
        linie[0]=listaMasiniTunsIarba.get(i).getBrand();
        linie[1]=listaMasiniTunsIarba.get(i).getModel();
        linie[2]=listaMasiniTunsIarba.get(i).getTipAlimentare();
        linie[3]=listaMasiniTunsIarba.get(i).getPutereMotor();
        linie[4]=listaMasiniTunsIarba.get(i).getTipPornire();
        linie[5]=listaMasiniTunsIarba.get(i).getLatimeTaiere();
        linie[6]=listaMasiniTunsIarba.get(i).getCuloare();
        linie[7]=listaMasiniTunsIarba.get(i).getPret();
        linie[8]=listaMasiniTunsIarba.get(i).getGarantie();
        linie[9]=listaMasiniTunsIarba.get(i).getCategorie();
        model.addRow(linie);
    }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiDenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiDenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiDenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiDenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold 
                 try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\denia\\Documents\\tttt\\Device\\DateMasiniTunsIarba.csv"))) {
                  String line;
                 while ((line = br.readLine()) != null) {
                
                      String[] parts = line.split(",");
                      String brand = parts[0];
                      String model = parts[1];
                      String tipAlimentare = parts[2];
                      float putere = Float.parseFloat(parts[3]);
                      String tipPornire = parts[4];
                      byte greutate = Byte.parseByte(parts[5].trim());
                      String culoare = parts[6];
                      float pret = Float.parseFloat(parts[7]);
                      byte garantie = Byte.parseByte(parts[8].trim());
                      String categorie = parts[9];
                
                
                        MasinaTunsIarba masina = new MasinaTunsIarba(brand, model, tipAlimentare, putere, tipPornire, greutate, culoare, pret, garantie, categorie);
                        listaMasiniTunsIarba.add(masina); lengthMasiniTunsIarbaArray++;
            }} catch (IOException e) {
            e.printStackTrace();
        }
                 
                 
                 try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\denia\\Documents\\tttt\\Device\\DateMotosapa.csv"))) {
                  String line;
                 while ((line = br.readLine()) != null) {//String brand,String model, String tipPornire, String tipAlimentare, int capacitateCilindrica, byte putereMotor, byte numarViteze,  float pret, byte garantie, String categorie
                        String[] parts = line.split(",");
                        
                        String brand = parts[0];
                        String model = parts[1];
                        String tipPornire = parts[2];
                        String tipAlimentare = parts[3];
                        int capacitateCilindrica = Integer.parseInt(parts[4]);
                        byte putereMotor = Byte.parseByte(parts[5]);
                        byte numarViteze = Byte.parseByte(parts[6]);
                        float pret = Float.parseFloat(parts[7]);
                        byte garantie = Byte.parseByte(parts[8]);
                        String categorie = parts[9];

                        Motosapa motosapa = new Motosapa(brand, model, tipPornire,tipAlimentare, capacitateCilindrica, putereMotor, numarViteze, pret, garantie,categorie);
                        
                        listaMotosapa.add(motosapa); lengthMotosapeArray++;
            }} catch (IOException e) {
            e.printStackTrace();
        }
                 
        //System.out.println(listaMasiniTunsIarba);
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiDenis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ClearTableButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton SalvareButon;
    private javax.swing.JButton SaveListaMotosapeButton;
    private javax.swing.JButton addMotosapaButton;
    private javax.swing.JButton afisareTabelMotosapeButton;
    private javax.swing.JTextField alimentareText;
    private javax.swing.JTextField brandMotosapaText;
    private javax.swing.JTextField brandText;
    private javax.swing.JTextField capacitateCilindricaMotosapaText;
    private javax.swing.JTextField categorieMotosapaText;
    private javax.swing.JTextField categorieText;
    private javax.swing.JTextField culoareText;
    private javax.swing.JButton deleteMotosapaButton;
    private javax.swing.JButton eliberareTableMotosapeButton;
    private javax.swing.JTextField garantieMotosapaText;
    private javax.swing.JTextField garantieText;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField latimeTaiereFiltrare;
    private javax.swing.JTextField latimeTaiereText;
    private static javax.swing.JTable masiniTunsIarba;
    private javax.swing.JTextField modelMotosapaText;
    private javax.swing.JTextField modelText;
    private javax.swing.JTable motosapeTable;
    private javax.swing.JTextField numarVitezeMotosapaText;
    private javax.swing.JButton populateTableButton;
    private javax.swing.JTextField pornireText;
    private javax.swing.JTextField pretFiltrare;
    private javax.swing.JTextField pretMotosapaFilter;
    private javax.swing.JTextField pretMotosapaText;
    private javax.swing.JTextField pretText;
    private javax.swing.JTextField putereFiltrare;
    private javax.swing.JTextField putereMotorMotosapaText;
    private javax.swing.JTextField putereText;
    private javax.swing.JButton sortButton;
    private javax.swing.JTextField tipAlimentareMotosapaText;
    private javax.swing.JTextField tipAlimentareMotosapeFilter;
    private javax.swing.JTextField tipPornireMotosapaFiltrare;
    private javax.swing.JTextField tipPornireMotosapaText;
    // End of variables declaration//GEN-END:variables
}
